/* read in data */
proc import datafile='/home/cjnava0/sasuser.v94/MSDS 6372/Project/bank-additional.csv'
	dbms=dlm out=life_expectancy replace;
	delimiter=';';
	getnames=yes;
run;


* CORRELATION MATRIX;
* CODE FROM HTTPS://BLOGS.SAS.COM/CONTENT/SASDUMMY/2013/06/12/CORRELATIONS-MATRIX-HEATMAP-WITH-SAS/;

%MACRO PREPCORRDATA(IN=,OUT=);
  /* RUN CORR MATRIX FOR INPUT DATA, ALL NUMERIC VARS */
  PROC CORR DATA=&IN. NOPRINT
    PEARSON
    OUTP=WORK._TMPCORR
    VARDEF=DF
  ;
  RUN;
 
  /* PREP DATA FOR HEAT MAP */
DATA &OUT.;
  KEEP X Y R;
  SET WORK._TMPCORR(WHERE=(_TYPE_="CORR"));
  ARRAY V{*} _NUMERIC_;
  X = _NAME_;
  DO I = DIM(V) TO 1 BY -1;
    Y = VNAME(V(I));
    R = V(I);
    /* CREATES A LOWER TRIANGULAR MATRIX */
    IF (I<_N_) THEN
      R=.;
    OUTPUT;
  END;
RUN;
 
PROC DATASETS LIB=WORK NOLIST NOWARN;
  DELETE _TMPCORR;
QUIT;
%MEND;

ODS PATH WORK.MYSTORE(UPDATE) SASHELP.TMPLMST(READ);ODS GRAPHICS ON;


PROC TEMPLATE;
  DEFINE STATGRAPH CORRHEATMAP;
   DYNAMIC _TITLE;
    BEGINGRAPH;
      ENTRYTITLE _TITLE;
      RANGEATTRMAP NAME='MAP';
      RANGE -1 - 1 / RANGECOLORMODEL=(CXD8B365 CXF5F5F5 CX5AB4AC);
      ENDRANGEATTRMAP;
      RANGEATTRVAR VAR=R ATTRVAR=R ATTRMAP='MAP';
      LAYOUT OVERLAY / 
        XAXISOPTS=(DISPLAY=(LINE TICKS TICKVALUES)) 
        YAXISOPTS=(DISPLAY=(LINE TICKS TICKVALUES));
        HEATMAPPARM X = X Y = Y COLORRESPONSE = R / 
          XBINAXIS=FALSE YBINAXIS=FALSE
          NAME = "HEATMAP" DISPLAY=ALL;
        CONTINUOUSLEGEND "HEATMAP" / 
          ORIENT = VERTICAL LOCATION = OUTSIDE TITLE="PEARSON CORRELATION";
      ENDLAYOUT;
    ENDGRAPH;
  END;
RUN;

ODS GRAPHICS /HEIGHT=1500 WIDTH=2000 IMAGEMAP;

%PREPCORRDATA(IN=life_expectancy1 ,OUT=CORR_MATRIX);

/* include the correlation plot in the write-up*/
PROC SGRENDER DATA=CORR_MATRIX TEMPLATE=CORRHEATMAP;
   DYNAMIC _TITLE_="CORR MATRIX";
   TITLE1 'CORRELATION MATRIX';
RUN;

proc sgscatter data=life_expectancy1;
matrix  life_expectancy infant_deaths1 under_5_deaths1 neonatal_deaths1 adult_mortality1
		/ diagonal=(histogram);
run;












