ODS GRAPHICS ON;
 
* READ IN DATA;
PROC IMPORT DATAFILE='/home/cjnava0/sasuser.v94/MSDS 6372/Project/product_sales.csv'
 	DBMS=DLM OUT=SALES REPLACE;
 	DELIMITER=',';
 	GETNAMES=YES;
RUN;
 
* FILTER TO ONE ITEM AT ONE STORE;
DATA SALES1;
 	SET SALES;
 	IF STORE=1;
 	IF ITEM=1;
 	DROP STORE ITEM;
RUN;
 
PROC SGPLOT DATA=SALES1;
 	TITLE "Daily Product Sales";
 	SERIES X=DATE Y=SALES;
RUN;
 
* RUN INITAL MODEL TO SEE ACF AND PACF PLOTS TO HELP CHECK STATIONARITY;
* PLOTS SHOW THE DATASET IS NONSTATIONARY;
PROC AUTOREG DATA=SALES1 ALL PLOTS(UNPACK);
 	MODEL SALES= ;   	
 	OUTPUT OUT=P P=YHAT  PM=YTREND LCL=LCL UCL=UCL;
RUN;
 
PROC ARIMA DATA=SALES1 PLOTS;
 	IDENTIFY VAR=SALES(1);
 	ESTIMATE METHOD=CLS P=(7 14 21 28 35) Q=(1) ; 
 	FORECAST LEAD=30 BACK=30 ID=DATE INTERVAL=DAY;
 	OUTLIER;
 	RUN;
QUIT;